INSERT INTO EMPLOYEES(ID, NAME, MIDDLE_INITIAL, LAST_NAME, EMAIL, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS) VALUES(1, 'Alejandro', 'Bautista', 'Mendoza', 'lexabame@gmail.com', '1987-04-22', '2014-01-01', 'ACTIVE');

INSERT INTO EMPLOYEES(ID, NAME, MIDDLE_INITIAL, LAST_NAME, EMAIL, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS) VALUES(2, 'Juan Gualberto', 'Bautista', 'Mendoza', 'juan@gmail.com', '1988-07-12', '2015-01-01', 'ACTIVE');

INSERT INTO EMPLOYEES(ID, NAME, MIDDLE_INITIAL, LAST_NAME, EMAIL, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS) VALUES(3, 'David', 'Bautista', 'Mendoza', 'david@gmail.com', '1990-10-28', '2016-01-01', 'ACTIVE');

INSERT INTO EMPLOYEES(ID, NAME, MIDDLE_INITIAL, LAST_NAME, EMAIL, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS) VALUES(4, 'Daniel', 'Bautista', 'Mendoza', 'daniel@gmail.com', '1993-02-09', '2017-01-01', 'ACTIVE');

INSERT INTO EMPLOYEES(ID, NAME, MIDDLE_INITIAL, LAST_NAME, EMAIL, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS) VALUES(5, 'Misael', 'Bautista', 'Mendoza', 'misael@gmail.com', '1994-02-20', '2018-01-01', 'ACTIVE');
