INSERT INTO EMPLOYEES(ID, NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, STATUS) VALUES(1, 'Alejandro', 'Bautista', 'Mendoza', '1987-04-22','ACTIVE');

INSERT INTO EMPLOYEES(ID, NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, STATUS) VALUES(2, 'Juan Gualberto', 'Bautista', 'Mendoza', '1988-07-12','ACTIVE');

INSERT INTO EMPLOYEES(ID, NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, STATUS) VALUES(3, 'David', 'Bautista', 'Mendoza', '1990-10-28','ACTIVE');

INSERT INTO EMPLOYEES(ID, NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, STATUS) VALUES(4, 'Daniel', 'Bautista', 'Mendoza', '1993-02-09','ACTIVE');

INSERT INTO EMPLOYEES(ID, NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, STATUS) VALUES(5, 'Misael', 'Bautista', 'Mendoza', '1994-02-20','ACTIVE');
