DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
	ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	MIDDLE_INITIAL VARCHAR(225),
	LAST_NAME VARCHAR(225),
	DATE_OF_BIRTH DATETIME,
	STATUS VARCHAR(50)
);